---
title: "TEMPEST Sensitivity Analysis"
output: html_document
date: "2023-11-13"
---

```{r setup, include=FALSE}

pacman::p_load(dplyr, FME, tidyr, ggplot2, relaimpo, readr)
theme_set(theme_bw())

# Define constants
NUM_YEARS <- 1
NUM_RUNS <- 100                                                                                                     

# Define palette
# output_palette <- c("AGG" = "#543005", "CO2" = "#8C510A", "MIC" = "#35978F", 
#                     "LMWC" = "#1E3C6E", "POM" = "#2A6A7F", "MAOM" = "#704108")


# Define pool long names
pools <- c("AGG" = "Aggregate~C~(gC~m^-2)",
           "CO2_emissions" = "CO2~emissions~(gC~m^-2~day^-1)",
           "MIC" = "Microbial~biomass~(gC~m^-2)",
           "LMWC" = "Low~molecular~weight~C~(gC~m^-2)",
           "POM" = "Particulate~organic~matter~(gC~m^-2)",
           "MAOM" = "Mineral~associated~organic~matter~(gC~m^-2)")

param_names <- c("param_bulkd" = "Bulk Density", "param_claysilt" = "ClaySilt", "param_pH" = "pH")
force_names <- c("forc_npp" = "Net~Primary~Production~(gC~m^2)", "forc_st" = "Soil~Temperature~(°C)", "forc_sw" = "Soil~Moisture~(m^3m^-3)")

param_units <- c("param_bulkd" = "Bulk~Density~(kg~m^3)", "param_claysilt" = "ClaySilt~'(%)'", "param_pH" = "pH~(unitless)")

# Read forcing data
tmp_forcing_data <- read_csv("tmp_forcing_data.csv")

tmp_forcing_data %>% 
  pivot_longer(cols = !DOY) %>% 
  ggplot(aes(x = DOY, y = value)) +
  geom_line(color = "#35978F", linewidth = 0.7) + 
  facet_wrap(~name, scales = "free", labeller = labeller(name = as_labeller(force_names, label_parsed))) +
  labs(x = "Day of Year", y = "") +
  theme_minimal(base_size = 24)

# Read in parameters - Described in Table A1 of Abramoff et al. (2021)
parameters.file <- read.table("./input/model input/soilpara_in_fit.txt") %>% 
  add_row(V1 = "param_pc", V2 = 0.86) # quick fix, add back in param_pc since were using the example file
parameters <- as.list(parameters.file$V2)
names(parameters) <- parameters.file$V1

# Read in functions
source("./functions/run_functions.R") # R script that contains calls to run model
source("./functions/derivs_V2_MM.R") # The official version of Millennial V2

set.seed(15)

# Create a runlist to vary select parameters
generate_params <- function(run_numbers){
  nruns <- length(run_numbers)
  tibble(
    run_number = run_numbers,
    #numbers taken from SoilGrids at the 2-15cm depth
    param_pH = rnorm(n = nruns, mean = 4.9, sd = 0.6), # pH, adjusted to average of site values
    param_bulkd = rnorm(n = nruns, mean = 1280, sd = 90), # bulk density in kg soil m-3
    param_claysilt = rnorm(n = nruns, mean = 66.6, sd = 5)  # clay and silt content in %
  )
}

# Generate 100 unique runs
runs <- 1:NUM_RUNS
runlist <- as.list(generate_params(runs))

# Function to create vectors for all the existing fixed parameters
params_fixed <- list()
for(p in names(parameters)){
  params_fixed[[p]] <- rep_len(parameters[[p]], length.out = length(runs))
}

# Combine the two lists
runlist_final <- c(runlist, params_fixed)


```

```{r parameters, include=FALSE}
tibble(
  param_pH_median = 4.9, param_pH_sd = 0.6,
  param_bulkd_median = 1280, param_bulkd_sd = 90,
  param_claysilt_median = 66.6, param_claysilt_sd = 5) %>% 
  pivot_longer(cols = is.numeric, names_to = c("parameter", ".value"), 
               names_pattern = "(.*)_(.*)") -> param_stats

bind_rows(runlist) %>% 
  pivot_longer(cols = !run_number, names_to = "parameter", values_to = "value") %>% 
  ggplot() + 
  geom_vline(data = param_stats, aes(xintercept = median), color = "grey40") +
  geom_density(aes(x = value), fill = "#A7DCD0", color = "#35978F", alpha = 0.7) + 
  facet_wrap(~parameter, scales = "free", 
             labeller = labeller(parameter = as_labeller(param_units, label_parsed))) + 
  labs(x = "Value", y = "Density") +
  theme_minimal(base_size = 24)

```

```{r run-analysis, include=FALSE}
# Run the model
output <- list()
for(r in runs){
  # To access parameter values:
  # First, we want to drop the run number, so we pass in runlist_final[-1] to
  # remove the first element of the list.
  # Then, we need to access the list of parameter values for each run.
  # We can extract this from the list by looping through each run number and
  # pulling out that column from each list element. i.e., the first column
  # corresponds to run 1, second column to run 2, etc.
  params <- lapply(runlist_final[-1], `[`, r) # could also use mapply for this

  # Run Millenial
  output[[r]] <- as.data.frame(Run_Model(tmp_forcing_data,
                           derivs_V2_MM,
                           params,
                           num.years = NUM_YEARS,
                           # This can be adjusted to run a steady state
                           state = c(POM = 1, LMWC = 1, AGG = 1, MIC = 1, MAOM = 1, CO2 = 0)))

  # Re-assign run number column now that the model has run
  output[[r]]$run_number <- r
}

# Combine data
model_output <- bind_rows(output) %>% as_tibble() %>% 
  mutate(CO2_emissions = c(NA, diff(CO2))) %>% #calculate co2 emission rate
  dplyr::select(-CO2)


# Plot just the model outputs as a ribbon plot
# Clean up data

ribbon_plot_data <- model_output %>%
  pivot_longer(cols = c(POM, LMWC, AGG, MIC, MAOM, CO2_emissions),
               names_to = "metric",
               values_to = "values") %>%
  group_by(time, metric) %>%
  summarize(sd = sd(values),
            min = min(values),
            max = max(values),
            median = median(values),
            .groups = "drop")

# Plot
ribbon_plot_data %>%
  ggplot(aes(x = time)) +
  geom_ribbon(aes(ymin = min, ymax = max), fill = "#1E3C6E", alpha = 0.5) +
  geom_line(aes(y = median), color = "#1E3C6E") +
  facet_wrap(~metric, scales = "free_y", ncol = 2, labeller = labeller(metric = as_labeller(pools, label_parsed))) +
  labs(x = "Time (days)", y = "") +
  # y = expression(paste("gC ", m^{-2}))
  theme_minimal(base_size = 24)

# ggsave("./figures/model_outputs.jpg", height = 6, width = 9)
```


```{r rel-importance, include=FALSE}

# Calculate relative importance
# Define function
calc_relimp <- function(x) {

    t <- x$time # record time...
    x$time <- NULL # and drop time column
    run <- x$run_number[1] # record run number
    x$run_number <- NULL # drop run number column
    n <- x$name # record parameter name
    x$name <- NULL # and drop

    # Fit model. The formula notation means "CO2 as a
    # function of all other terms" (which is why we dropped year)
    lin <- lm(param ~ ., data = x)

    # Calculate relative importance metrics and extract 'lmg' results
    # 'lmg' is the R^2 contribution averaged over orderings among regressors;
    # should sum to one because we're using relative importances (rela=TRUE)
    # If the function can't solve, return a try error and continue running
    relimp <- try(calc.relimp(lin, type = "lmg", rela = TRUE)@lmg)
    if(class(relimp) == "try-error") {
      message(t, " calc.relimp error")
      return(NULL)
    }

    # Return a data frame: time, parameter, relative importance
    tibble(time = unique(t),
           output = names(relimp),
           value = relimp,
           source = n[1])
}

# Create a dataframe to pass to relative importance function
importance_test <- model_output %>%
  left_join(bind_rows(runlist), by = "run_number")

# We want to look at all of the outputs, define here to loop through
out_params <- c("POM", "LMWC", "AGG", "MIC", "MAOM", "CO2_emissions")

# Create a list to store results
out <- list()
for(p in out_params){
  # Isolate one output at a time and get only the parameters we vary
  importance_test_filter <- importance_test %>%
    dplyr::select(c(run_number, time, p, starts_with("param_"))) %>%
    # Rename the param column to the output variable of interest...
    rename(param = p) %>%
    # ...and create a new column to preserve its name
    mutate(name = p)
  # Split the data up by day to calculate variance for each timestep
  imp <- split(importance_test_filter, list(importance_test_filter$time))
  # (except for the first day, where outputs = 1 and 0;
  # note this can be changed in the "run model" function)
  out[[p]] <- lapply(imp[-1], FUN = calc_relimp) %>% bind_rows()
}

# Plot relative importance
bind_rows(out) %>%
  ggplot(aes(x = time, y = value, fill = output)) +
  geom_area() +
  facet_wrap(~source, ncol = 2, labeller = labeller(source = as_labeller(pools, label_parsed))) +
  labs(x = "Time (days)",
       y = "Relative Importance",
       fill = "Parameter") +
  # Adjust the zoom as needed - need to zoom out with longer runs
  coord_cartesian(ylim = c(0.99, 1.0)) +
  scale_fill_manual(values = pals::brewer.set2(n = 5), labels = param_names) +
  # vertical lines show with NPP starts and stops
  #geom_vline(xintercept = c(168, 260), linetype = 2) +
  theme_minimal(base_size = 24) +
  theme(legend.position = "bottom")

```
